// Fixed IPC channel names. Every channel is prefixed with `bureau:`.
// No dynamic channel names may be constructed outside this map.

export const IPC_CHANNELS = {
  APP_GET_CAPABILITIES: 'bureau:app:getCapabilities',
  APP_WINDOW_MINIMIZE: 'bureau:app:minimizeWindow',
  APP_WINDOW_TOGGLE_MAXIMIZE: 'bureau:app:toggleMaximizeWindow',
  APP_WINDOW_CLOSE: 'bureau:app:closeWindow',
  // Close/quit handshake. Main asks the renderer to confirm when processes are alive;
  // the renderer answers with confirm (graceful shutdown) or cancel (abort the close).
  APP_CLOSE_REQUESTED: 'bureau:app:closeRequested',
  APP_CONFIRM_QUIT: 'bureau:app:confirmQuit',
  APP_CANCEL_QUIT: 'bureau:app:cancelQuit',
  APP_SET_DIRTY_FILES: 'bureau:app:setDirtyFiles',
  APP_UPDATES_GET_STATE: 'bureau:app:updates:getState',
  APP_UPDATES_CHECK: 'bureau:app:updates:check',
  APP_UPDATES_INSTALL: 'bureau:app:updates:install',
  APP_UPDATES_STATE_EVENT: 'bureau:app:updates:state',
  // Main → renderer graceful-shutdown handshake.
  APP_SHUTDOWN_BEGIN: 'bureau:app:shutdownBegin',
  APP_SHUTDOWN_PROGRESS: 'bureau:app:shutdownProgress',

  PROJECTS_LIST: 'bureau:projects:list',
  PROJECTS_ADD: 'bureau:projects:add',
  PROJECTS_DETECT: 'bureau:projects:detect',
  PROJECTS_REMOVE: 'bureau:projects:remove',
  PROJECTS_TOUCH: 'bureau:projects:touch',
  PROJECTS_SET_PINNED: 'bureau:projects:setPinned',
  PROJECTS_REORDER_PINNED: 'bureau:projects:reorderPinned',

  FILES_LIST_DIRECTORY: 'bureau:files:listDirectory',
  FILES_READ_TEXT: 'bureau:files:readText',
  FILES_READ_IMAGE: 'bureau:files:readImage',
  FILES_SAVE_TEXT: 'bureau:files:saveText',
  FILES_CREATE_ENTRY: 'bureau:files:createEntry',
  FILES_RENAME_ENTRY: 'bureau:files:renameEntry',
  FILES_MOVE_ENTRY: 'bureau:files:moveEntry',
  FILES_DUPLICATE_ENTRY: 'bureau:files:duplicateEntry',
  FILES_TRASH_ENTRY: 'bureau:files:trashEntry',
  FILES_QUICK_OPEN: 'bureau:files:quickOpen',
  FILES_START_SEARCH: 'bureau:files:startSearch',
  FILES_CANCEL_SEARCH: 'bureau:files:cancelSearch',
  FILES_WATCH_PROJECT: 'bureau:files:watchProject',
  FILES_UNWATCH_PROJECT: 'bureau:files:unwatchProject',
  FILES_RESOLVE_MARKDOWN_ASSET: 'bureau:files:resolveMarkdownAsset',
  FILES_FETCH_REMOTE_IMAGE: 'bureau:files:fetchRemoteImage',
  FILES_OPEN_EXTERNAL: 'bureau:files:openExternal',
  FILES_REVEAL: 'bureau:files:reveal',
  FILES_EXPORT_HTML: 'bureau:files:exportHtml',
  FILES_EXPORT_PDF: 'bureau:files:exportPdf',
  FILES_PRINT_DOCUMENT: 'bureau:files:printDocument',
  FILES_GET_WORKSPACE_STATE: 'bureau:files:getWorkspaceState',
  FILES_SAVE_WORKSPACE_STATE: 'bureau:files:saveWorkspaceState',
  FILES_PUT_DRAFT: 'bureau:files:putDraft',
  FILES_REMOVE_DRAFT: 'bureau:files:removeDraft',
  FILES_LIST_DRAFTS: 'bureau:files:listDrafts',
  FILES_EVENT: 'bureau:files:event',
  FILES_SEARCH_EVENT: 'bureau:files:searchEvent',

  PROCESSES_LIST: 'bureau:processes:list',
  PROCESSES_REDETECT: 'bureau:processes:redetect',
  PROCESSES_START: 'bureau:processes:start',
  PROCESSES_STOP: 'bureau:processes:stop',
  PROCESSES_RESTART: 'bureau:processes:restart',
  PROCESSES_STOP_ALL: 'bureau:processes:stopAll',
  PROCESSES_GET_LOG: 'bureau:processes:getLog',
  PROCESSES_SAVE_DEFINITION: 'bureau:processes:saveDefinition',
  PROCESSES_REMOVE_DEFINITION: 'bureau:processes:removeDefinition',
  // Main → renderer streaming events.
  PROCESSES_OUTPUT_EVENT: 'bureau:processes:output',
  PROCESSES_STATUS_EVENT: 'bureau:processes:status',

  PREVIEW_SET_BOUNDS: 'bureau:preview:setBounds',
  PREVIEW_NAVIGATE: 'bureau:preview:navigate',
  PREVIEW_RELOAD: 'bureau:preview:reload',
  PREVIEW_RELOAD_HARD: 'bureau:preview:reloadHard',
  PREVIEW_BACK: 'bureau:preview:back',
  PREVIEW_FORWARD: 'bureau:preview:forward',
  PREVIEW_SET_VISIBLE: 'bureau:preview:setVisible',
  PREVIEW_OPEN_EXTERNAL: 'bureau:preview:openExternal',
  PREVIEW_OPEN_DEVTOOLS: 'bureau:preview:openDevTools',
  PREVIEW_SET_ZOOM: 'bureau:preview:setZoom',
  PREVIEW_CLEAR_CONSOLE: 'bureau:preview:clearConsole',
  PREVIEW_STATE_EVENT: 'bureau:preview:state',
  PREVIEW_HOTKEY_EVENT: 'bureau:preview:hotkey',
  PREVIEW_CONSOLE_EVENT: 'bureau:preview:console',

  PROCESSES_PTY_WRITE: 'bureau:processes:ptyWrite',
  PROCESSES_PTY_RESIZE: 'bureau:processes:ptyResize',
  PROCESSES_PTY_EVENT: 'bureau:processes:pty',

  // Embedded shell sessions (the Terminal tab).
  TERMINAL_LIST: 'bureau:terminal:list',
  TERMINAL_CREATE: 'bureau:terminal:create',
  TERMINAL_CLOSE: 'bureau:terminal:close',
  TERMINAL_RENAME: 'bureau:terminal:rename',
  TERMINAL_WRITE: 'bureau:terminal:write',
  TERMINAL_RESIZE: 'bureau:terminal:resize',
  TERMINAL_GET_BUFFER: 'bureau:terminal:getBuffer',
  // Main → renderer streaming events.
  TERMINAL_DATA_EVENT: 'bureau:terminal:data',
  TERMINAL_EXIT_EVENT: 'bureau:terminal:exit',

  SYSTEM_CHOOSE_DIRECTORY: 'bureau:system:chooseDirectory',
  SYSTEM_OPEN_IN_EDITOR: 'bureau:system:openInEditor',
  SYSTEM_OPEN_IN_TERMINAL: 'bureau:system:openInTerminal',
  SYSTEM_OPEN_IN_EXPLORER: 'bureau:system:openInExplorer',

  OPERATIONS_LIST: 'bureau:operations:list',
  OPERATIONS_CANCEL: 'bureau:operations:cancel',

  GIT_REFRESH: 'bureau:git:refresh',
  GIT_SNAPSHOT: 'bureau:git:snapshot',
  GIT_CLONE: 'bureau:git:clone',
  GIT_INIT: 'bureau:git:init',
  GIT_STAGE_FILE: 'bureau:git:stageFile',
  GIT_STAGE_ALL: 'bureau:git:stageAll',
  GIT_UNSTAGE_ALL: 'bureau:git:unstageAll',
  GIT_DISCARD_FILE: 'bureau:git:discardFile',
  GIT_DISCARD_ALL: 'bureau:git:discardAll',
  GIT_LIST_BRANCH_DETAILS: 'bureau:git:listBranchDetails',
  GIT_SWITCH_BRANCH: 'bureau:git:switchBranch',
  GIT_CREATE_BRANCH: 'bureau:git:createBranch',
  GIT_DELETE_BRANCH: 'bureau:git:deleteBranch',
  GIT_PUBLISH_BRANCH: 'bureau:git:publishBranch',
  GIT_SET_UPSTREAM: 'bureau:git:setUpstream',
  GIT_RENAME_BRANCH: 'bureau:git:renameBranch',
  GIT_CHECKOUT_TRACKING: 'bureau:git:checkoutTracking',
  GIT_DELETE_REMOTE_BRANCH: 'bureau:git:deleteRemoteBranch',
  GIT_MERGE_BRANCH: 'bureau:git:mergeBranch',
  GIT_REBASE_BRANCH: 'bureau:git:rebaseBranch',
  GIT_RESET_TO_COMMIT: 'bureau:git:resetToCommit',
  GIT_CHECKOUT_COMMIT: 'bureau:git:checkoutCommit',
  GIT_LIST_REMOTES: 'bureau:git:listRemotes',
  GIT_ADD_REMOTE: 'bureau:git:addRemote',
  GIT_RENAME_REMOTE: 'bureau:git:renameRemote',
  GIT_REMOVE_REMOTE: 'bureau:git:removeRemote',
  GIT_SET_REMOTE_URL: 'bureau:git:setRemoteUrl',
  GIT_FETCH: 'bureau:git:fetch',
  GIT_UNSTAGE_FILE: 'bureau:git:unstageFile',
  GIT_COMMIT: 'bureau:git:commit',
  GIT_PULL_FAST_FORWARD: 'bureau:git:pullFastForward',
  GIT_PUSH: 'bureau:git:push',
  GIT_STASH_PUSH: 'bureau:git:stashPush',
  GIT_STASH_POP: 'bureau:git:stashPop',
  GIT_STASH_DROP: 'bureau:git:stashDrop',
  GIT_STASH_LIST: 'bureau:git:stashList',
  GIT_STASH_LIST_FILES: 'bureau:git:stashListFiles',
  GIT_STASH_DIFF: 'bureau:git:stashDiff',
  GIT_STASH_APPLY: 'bureau:git:stashApply',
  GIT_STASH_BRANCH: 'bureau:git:stashBranch',
  GIT_STASH_RESTORE_FILES: 'bureau:git:stashRestoreFiles',
  GIT_GET_DIFF: 'bureau:git:getDiff',
  GIT_LIST_COMMIT_FILES: 'bureau:git:listCommitFiles',
  GIT_LIST_HISTORY: 'bureau:git:listHistory',
  GIT_LIST_REFLOG: 'bureau:git:listReflog',
  GIT_COMPARE_COMMITS: 'bureau:git:compareCommits',
  GIT_CHERRY_PICK: 'bureau:git:cherryPick',
  GIT_REVERT_COMMIT: 'bureau:git:revertCommit',
  GIT_CREATE_BRANCH_FROM_COMMIT: 'bureau:git:createBranchFromCommit',
  GIT_LIST_TAGS: 'bureau:git:listTags',
  GIT_CREATE_TAG: 'bureau:git:createTag',
  GIT_DELETE_TAG: 'bureau:git:deleteTag',
  GIT_PUSH_TAG: 'bureau:git:pushTag',
  GIT_DELETE_REMOTE_TAG: 'bureau:git:deleteRemoteTag',
  GIT_APPLY_HUNK: 'bureau:git:applyHunk',
  GIT_GET_OPERATION_STATE: 'bureau:git:getOperationState',
  GIT_GET_CONFLICT_VERSION: 'bureau:git:getConflictVersion',
  GIT_RESOLVE_CONFLICT: 'bureau:git:resolveConflict',
  GIT_MERGE_CONTINUE: 'bureau:git:mergeContinue',
  GIT_MERGE_ABORT: 'bureau:git:mergeAbort',
  GIT_REBASE_CONTINUE: 'bureau:git:rebaseContinue',
  GIT_REBASE_SKIP: 'bureau:git:rebaseSkip',
  GIT_REBASE_ABORT: 'bureau:git:rebaseAbort',
  GIT_CHERRY_PICK_CONTINUE: 'bureau:git:cherryPickContinue',
  GIT_CHERRY_PICK_SKIP: 'bureau:git:cherryPickSkip',
  GIT_CHERRY_PICK_ABORT: 'bureau:git:cherryPickAbort',
  GIT_REVERT_CONTINUE: 'bureau:git:revertContinue',
  GIT_REVERT_SKIP: 'bureau:git:revertSkip',
  GIT_REVERT_ABORT: 'bureau:git:revertAbort',
  GIT_BISECT_RESET: 'bureau:git:bisectReset',
  GIT_LIST_WORKTREES: 'bureau:git:listWorktrees',
  GIT_ADD_WORKTREE: 'bureau:git:addWorktree',
  GIT_REMOVE_WORKTREE: 'bureau:git:removeWorktree',
  GIT_LOCK_WORKTREE: 'bureau:git:lockWorktree',
  GIT_UNLOCK_WORKTREE: 'bureau:git:unlockWorktree',
  GIT_PRUNE_WORKTREES: 'bureau:git:pruneWorktrees',
  GIT_LIST_SUBMODULES: 'bureau:git:listSubmodules',
  GIT_BLAME: 'bureau:git:blame',
  GIT_SUBMODULE_INIT: 'bureau:git:submoduleInit',
  GIT_SUBMODULE_UPDATE: 'bureau:git:submoduleUpdate',

  GITHUB_GET_STATUS: 'bureau:github:getStatus',
  GITHUB_SIGN_IN: 'bureau:github:signIn',
  GITHUB_PUBLISH: 'bureau:github:publish',
  GITHUB_OPEN_URL: 'bureau:github:openUrl',

  GITEA_GET_STATUS: 'bureau:gitea:getStatus',
  GITEA_CONNECT: 'bureau:gitea:connect',
  GITEA_DISCONNECT: 'bureau:gitea:disconnect',
  GITEA_PUBLISH: 'bureau:gitea:publish',

  ANDROID_GET_OVERVIEW: 'bureau:android:getOverview',
  ANDROID_CHOOSE_SDK: 'bureau:android:chooseSdk',
  ANDROID_CHOOSE_SCRCPY: 'bureau:android:chooseScrcpy',
  ANDROID_ADB_RESTART: 'bureau:android:adb:restart',
  ANDROID_CHOOSE_APK: 'bureau:android:chooseApk',
  ANDROID_CHOOSE_RECORDING: 'bureau:android:chooseRecording',
  ANDROID_AVD_START: 'bureau:android:avd:start',
  ANDROID_AVD_STOP: 'bureau:android:avd:stop',
  ANDROID_AVD_BOOT_STATUS: 'bureau:android:avd:bootStatus',
  ANDROID_DEVICES_LIST: 'bureau:android:devices:list',
  ANDROID_APK_INSTALL: 'bureau:android:apk:install',
  ANDROID_APK_LAUNCH: 'bureau:android:apk:launch',
  ANDROID_APK_UNINSTALL: 'bureau:android:apk:uninstall',
  ANDROID_PACKAGES_LIST: 'bureau:android:packages:list',
  ANDROID_LOGCAT_START: 'bureau:android:logcat:start',
  ANDROID_LOGCAT_STOP: 'bureau:android:logcat:stop',
  ANDROID_LOGCAT_PAUSE: 'bureau:android:logcat:pause',
  ANDROID_LOGCAT_CLEAR: 'bureau:android:logcat:clear',
  ANDROID_LOGCAT_SNAPSHOT: 'bureau:android:logcat:snapshot',
  ANDROID_LOGCAT_EXPORT: 'bureau:android:logcat:export',
  ANDROID_LOGCAT_EVENT: 'bureau:android:logcat:event',
  ANDROID_SCRCPY_START: 'bureau:android:scrcpy:start',
  ANDROID_SCRCPY_STOP: 'bureau:android:scrcpy:stop',
  ANDROID_FLUTTER_RUN: 'bureau:android:flutter:run',
  ANDROID_REACT_NATIVE_STATUS: 'bureau:android:reactNative:status',
  ANDROID_REACT_NATIVE_METRO_START: 'bureau:android:reactNative:metro:start',
  ANDROID_REACT_NATIVE_METRO_STOP: 'bureau:android:reactNative:metro:stop',
  ANDROID_REACT_NATIVE_RUN: 'bureau:android:reactNative:run',
  ANDROID_REACT_NATIVE_REVERSE: 'bureau:android:reactNative:reverse',
  ANDROID_REACT_NATIVE_RELOAD: 'bureau:android:reactNative:reload',
  ANDROID_REACT_NATIVE_DEV_MENU: 'bureau:android:reactNative:devMenu',
  ANDROID_DISPLAY_START: 'bureau:android:display:start',
  ANDROID_DISPLAY_STOP: 'bureau:android:display:stop',
  ANDROID_DISPLAY_MOUSE: 'bureau:android:display:mouse',
  ANDROID_DISPLAY_KEY: 'bureau:android:display:key',
  ANDROID_DISPLAY_BUTTON: 'bureau:android:display:button',
  ANDROID_DISPLAY_ROTATE: 'bureau:android:display:rotate',
  ANDROID_DISPLAY_PASTE: 'bureau:android:display:paste',
  ANDROID_DISPLAY_SCREENSHOT: 'bureau:android:display:screenshot',
  ANDROID_DISPLAY_EVENT: 'bureau:android:display:event',
  ANDROID_SNAPSHOT_LIST: 'bureau:android:snapshot:list',
  ANDROID_SNAPSHOT_SAVE: 'bureau:android:snapshot:save',
  ANDROID_SNAPSHOT_LOAD: 'bureau:android:snapshot:load',
  ANDROID_GEO_FIX: 'bureau:android:geo:fix',

  SETTINGS_GET: 'bureau:settings:get',
  SETTINGS_UPDATE: 'bureau:settings:update',
  SETTINGS_CHOOSE_CUSTOM_EDITOR: 'bureau:settings:chooseCustomEditor',
  SETTINGS_SET_EDITOR_PRESET: 'bureau:settings:setEditorPreset',
  SETTINGS_CHOOSE_CUSTOM_TERMINAL: 'bureau:settings:chooseCustomTerminal',
  SETTINGS_SET_TERMINAL_PRESET: 'bureau:settings:setTerminalPreset',
  SETTINGS_CHOOSE_GIT_EXECUTABLE: 'bureau:settings:chooseGitExecutable',
  SETTINGS_CLEAR_GIT_EXECUTABLE: 'bureau:settings:clearGitExecutable',

  TOOLCHAINS_GET: 'bureau:toolchains:get',
  TOOLCHAINS_SET_ACTIVE: 'bureau:toolchains:setActive',

  PORTS_LIST: 'bureau:ports:list',
  PORTS_KILL: 'bureau:ports:kill',

  TASKS_LIST: 'bureau:tasks:list',
  TASKS_RUN: 'bureau:tasks:run',

  /** API workbench — Phase 1 persistence and REST. */
  API_LIST_WORKSPACES: 'bureau:api:listWorkspaces',
  API_GET_STATUS: 'bureau:api:getStatus',
  API_GET_WORKSPACE: 'bureau:api:getWorkspace',
  API_CREATE_WORKSPACE: 'bureau:api:createWorkspace',
  API_UPDATE_WORKSPACE: 'bureau:api:updateWorkspace',
  API_DELETE_WORKSPACE: 'bureau:api:deleteWorkspace',
  API_CREATE_COLLECTION: 'bureau:api:createCollection',
  API_UPDATE_COLLECTION: 'bureau:api:updateCollection',
  API_DELETE_COLLECTION: 'bureau:api:deleteCollection',
  API_SAVE_REQUEST: 'bureau:api:saveRequest',
  API_DELETE_REQUEST: 'bureau:api:deleteRequest',
  API_CREATE_ENVIRONMENT: 'bureau:api:createEnvironment',
  API_UPDATE_ENVIRONMENT: 'bureau:api:updateEnvironment',
  API_DELETE_ENVIRONMENT: 'bureau:api:deleteEnvironment',
  API_LIST_SECRETS: 'bureau:api:listSecrets',
  API_SAVE_SECRET: 'bureau:api:saveSecret',
  API_DELETE_SECRET: 'bureau:api:deleteSecret',
  API_LIST_HISTORY: 'bureau:api:listHistory',
  API_GET_HISTORY_ENTRY: 'bureau:api:getHistoryEntry',
  API_SEND_REQUEST: 'bureau:api:sendRequest',
  API_CANCEL_REQUEST: 'bureau:api:cancelRequest',
  API_SET_DIRTY_DRAFT_COUNT: 'bureau:api:setDirtyDraftCount',
  API_SESSION_EVENT: 'bureau:api:sessionEvent',

  /** API workbench — Phase 2 streams, GraphQL, OAuth 2, and TLS profiles. */
  API_OPEN_STREAM: 'bureau:api:openStream',
  API_SEND_STREAM_MESSAGE: 'bureau:api:sendStreamMessage',
  API_CLOSE_STREAM: 'bureau:api:closeStream',
  API_SET_STREAM_PAUSED: 'bureau:api:setStreamPaused',
  API_GET_STREAM_SNAPSHOT: 'bureau:api:getStreamSnapshot',
  API_INTROSPECT_GRAPHQL: 'bureau:api:introspectGraphql',
  API_SAVE_TLS_PROFILE: 'bureau:api:saveTlsProfile',
  API_DELETE_TLS_PROFILE: 'bureau:api:deleteTlsProfile',
  API_SAVE_OAUTH_PROFILE: 'bureau:api:saveOauthProfile',
  API_DELETE_OAUTH_PROFILE: 'bureau:api:deleteOauthProfile',
  API_AUTHORIZE_OAUTH: 'bureau:api:authorizeOauth',
  API_CANCEL_OAUTH: 'bureau:api:cancelOauth',
  API_CLEAR_OAUTH_TOKEN: 'bureau:api:clearOauthToken',
  API_OAUTH_EVENT: 'bureau:api:oauthEvent',

  /** API workbench — Phase 3 import and export interoperability. */
  API_INSPECT_IMPORT: 'bureau:api:inspectImport',
  API_COMMIT_IMPORT: 'bureau:api:commitImport',
  API_DISCARD_IMPORT: 'bureau:api:discardImport',
  API_PLAN_EXPORT: 'bureau:api:planExport',
  API_COMMIT_EXPORT: 'bureau:api:commitExport',

  /** API workbench — Phase 4 script sandbox and collection runner. */
  API_VALIDATE_SCRIPT: 'bureau:api:validateScript',
  API_APPROVE_SCRIPTS: 'bureau:api:approveScripts',
  API_LIST_SCRIPT_LOCATIONS: 'bureau:api:listScriptLocations',
  API_LOAD_RUN_DATA: 'bureau:api:loadRunData',
  API_CLEAR_RUN_DATA: 'bureau:api:clearRunData',
  API_START_RUN: 'bureau:api:startRun',
  API_CANCEL_RUN: 'bureau:api:cancelRun',
  API_GET_RUN_REPORT: 'bureau:api:getRunReport',
  API_EXPORT_RUN_REPORT: 'bureau:api:exportRunReport',
  API_RUN_EVENT: 'bureau:api:runEvent',

  /** API workbench — Phase 5 proxy, cookie inspection, and backup/restore. */
  API_SAVE_PROXY_PROFILE: 'bureau:api:saveProxyProfile',
  API_DELETE_PROXY_PROFILE: 'bureau:api:deleteProxyProfile',
  API_LIST_COOKIE_JARS: 'bureau:api:listCookieJars',
  API_LIST_COOKIES: 'bureau:api:listCookies',
  API_DELETE_COOKIE: 'bureau:api:deleteCookie',
  API_CLEAR_COOKIES: 'bureau:api:clearCookies',
  API_SAVE_COOKIE: 'bureau:api:saveCookie',
  API_BACKUP_WORKSPACES: 'bureau:api:backupWorkspaces',
  API_PLAN_RESTORE: 'bureau:api:planRestore',
  API_COMMIT_RESTORE: 'bureau:api:commitRestore',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
